---
title: "Untitled"
author: "Thomas Caldwell"
date: "3/22/2017"
output: html_document
runtime: shiny
---

```{r}
library(leaflet)
library(dplyr)
library(ggplot2)
library(tidyr)
library(shiny)
```

```{r warning=FALSE}
library(readxl)
Mapping <- read_excel("~/Project-Damascus/data/Mapping.xlsx")
library(readr)
money_right <- read_csv("~/Project-Damascus/data/money-right.csv")
combined <- read.csv("~/Project-Damascus/data/combined.csv")
View(combined)
```

```{r}
fluidPage(
    
  # Copy the line below to make a select box 
  selectInput("condition", label = h3("Condition"), 
    choices = unique(combined$DRG.Definition), 
    selected = 1),
  
   # Copy the line below to make a select box 
  selectInput("state", label = h3("State"), 
    choices = unique(combined$Provider.State), 
    selected = 1),
  
  hr(),
  fluidRow(column(3, verbatimTextOutput("value")))
)

```

```{r}
hospitals <- data.frame(lat = combined$lat,
                        lon = combined$lon,
                        place = combined$name,
                        condition = combined$DRG.Definition,
                        state = combined$Provider.State,
                        stringsAsFactors = FALSE)
```

```{r}

hospitals %>%
  filter(condition %in% input$condition) %>%
  filter(state %in% input$state) %>%
      leaflet() %>% 
        setView(lng = -79.442778, lat = 37.783889, zoom = 1) %>%
        addTiles() %>%
        addCircleMarkers(popup = ~place, clusterOptions = markerClusterOptions())
```


```{r}
renderPlot({
 money_right %>%
    filter(`DRG Definition` %in% input$condition) %>%
    filter(`Provider State` %in% input$state) %>%
    ggplot(aes(`Provider Name`, `Average Total Payments`, fill = `Provider Name`)) + geom_bar(stat = "identity") + theme(axis.text.x = element_blank())
})
```

```{r}
  library(shiny)

ui <- fluidPage(
    
  # Copy the line below to make a select box 
  selectInput("condition", label = h3("Condition"), 
    choices = unique(money_right$`DRG Definition`), 
    selected = 1),
  
   # Copy the line below to make a select box 
  selectInput("state", label = h3("State"), 
    choices = unique(money_right$`Provider State`), 
    selected = 1),
  
   checkboxGroupInput("checkGroup", label = h3("Checkbox group"),
    choices = list("Average Covered Charges" = 1, "Average Total Payments" = 2, "Average Medicare Payments" = 3),
    selected = 1),
  
  hr(),
  fluidRow(column(3, verbatimTextOutput("value")))
  
  plotOutput(outputId = "bar")
)

  server <- function(input,output) {
  output$bar <- renderPlot({
    
    
  })
    
}
shinyApp(ui=ui, server=server)
  
  

```

