---
title: "Leaflet Fun"
author: "Thomas Caldwell"
date: "3/16/2017"
output: html_document
runtime: shiny
---

```{r}
library(leaflet)
library(dplyr)
library(ggplot2)
library(tidyr)
library(shiny)
```

```{r}
hospitals <- data.frame(lat = Map_Trial$lat[1:800],
                        lon = Map_Trial$lon[1:800],
                        place = Map_Trial$name[1:800],
                        stringsAsFactors = FALSE)
```

```{r}
leaflet(data = hospitals) %>% 
        setView(lng = -79.442778, lat = 37.783889, zoom = 1) %>%
        addTiles() %>%
        addCircleMarkers(popup = ~place, clusterOptions = markerClusterOptions())
```

```{r}
fluidPage(
    
  # Copy the line below to make a select box 
  selectInput("condition", label = h3("Condition"), 
    choices = unique(money_right$condition), 
    selected = 1),
  
   # Copy the line below to make a select box 
  selectInput("state", label = h3("State"), 
    choices = unique(money_right$state), 
    selected = 1),
  
   checkboxGroupInput("checkGroup", label = h3("Checkbox group"), 
    choices = list("Average Covered Charges" = 1, "Average Total Payments" = 2, "Average Medicare Payments" = 3),
    selected = 1),
  
  hr(),
  fluidRow(column(3, verbatimTextOutput("value")))
  
  
)
```

```{r}
renderPlot({
  money_right %>%
    filter(condition %in% input$condition, state %in% input$state) %>%
    group_by(`Provider Name`)
    summarise(n = n(),
              ave_payment = mean(`Average Covered Charges`+`Average Total Payments`+`Average Medicare Payments`, na.rm =                TRUE)) %>%
    ggplot(aes(ave_payment, color)) + geom_bar()
})
```


